Add AC_USE_SYSTEM_EXTENSIONS to expose non-standard extensions
Required on Solaris to expose definitions in system headers that
are not defined in the XPG standards now that xtrans 1.3 defines
_XOPEN_SOURCE to 600 on Solaris.

Fixes build failures:
gethost.c: In function ‘get_hostname’:
gethost.c:97:21: error: ‘INET6_ADDRSTRLEN’ undeclared (first use in this function)
gethost.c:97:21: note: each undeclared identifier is reported only once for each function it appears in
gethost.c:97:16: warning: unused variable ‘addr’ [-Wunused-variable]
gethost.c: In function ‘get_address_info’:
gethost.c:196:9: error: implicit declaration of function ‘strlcpy’ [-Werror=implicit-function-declaration]
gethost.c:196:9: warning: nested extern declaration of ‘strlcpy’ [-Wnested-externs]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Daniel Stone <daniel@fooishbar.org>